import type {
  Cliente,
  Comunicacion,
  Documento,
  Etapa,
  Municipio,
  Prospecto,
  Proyecto,
} from "@/types"

export const MUNICIPIOS_PRINCIPALES = [
  "Santiago",
  "Providencia",
  "Las Condes",
  "Maipú",
  "Ñuñoa",
  "Vitacura",
  "San Miguel",
  "Pudahuel",
  "La Florida",
  "Rancagua",
]

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: "c1",
    nombre: "Retail Andino SpA",
    rut: "76.123.456-7",
    contacto_nombre: "Carolina Fuentes",
    email: "carolina.fuentes@retailandino.cl",
    telefono: "+56 2 2345 6789",
    notas: "Cadena de tiendas de conveniencia en RM.",
    created_at: "2025-01-12",
  },
  {
    id: "c2",
    nombre: "Comercial Los Robles Ltda.",
    rut: "77.987.654-3",
    contacto_nombre: "Rodrigo Salinas",
    email: "rsalinas@losrobles.cl",
    telefono: "+56 9 8123 4567",
    notas: "Locales de farmacia.",
    created_at: "2025-02-03",
  },
  {
    id: "c3",
    nombre: "Inversiones Maipo S.A.",
    rut: "76.456.789-0",
    contacto_nombre: "Paula Henríquez",
    email: "paula.henriquez@maipo.cl",
    telefono: "+56 2 2987 1122",
    notas: "Desarrolladora de strip centers.",
    created_at: "2025-02-20",
  },
  {
    id: "c4",
    nombre: "Distribuidora Cordillera SpA",
    rut: "78.321.654-9",
    contacto_nombre: "Felipe Vergara",
    email: "fvergara@cordillera.cl",
    telefono: "+56 9 7654 3210",
    notas: "Supermercados de barrio.",
    created_at: "2025-03-05",
  },
  {
    id: "c5",
    nombre: "Grupo Aconcagua Retail",
    rut: "76.654.321-K",
    contacto_nombre: "María José Tapia",
    email: "mjtapia@aconcaguaretail.cl",
    telefono: "+56 2 2456 7788",
    notas: "Tiendas por departamento.",
    created_at: "2025-03-18",
  },
  {
    id: "c6",
    nombre: "Café Patagonia Ltda.",
    rut: "77.111.222-3",
    contacto_nombre: "Ignacio Morales",
    email: "ignacio@cafepatagonia.cl",
    telefono: "+56 9 9988 7766",
    notas: "Cafeterías de especialidad.",
    created_at: "2025-04-02",
  },
]

export const MOCK_PROYECTOS: Proyecto[] = [
  {
    id: "p1",
    cliente_id: "c1",
    nombre: "Tienda Retail Andino — Providencia",
    direccion: "Av. Providencia 1455, Local 3",
    municipio: "Providencia",
    tipo: "permiso_edificacion",
    estado: "en_revision",
    fecha_inicio: "2026-01-15",
    fecha_estimada: "2026-04-15",
    numero_expediente: "EXP-2026-0142",
    etapa_actual: "Revisión DOM",
    created_at: "2026-01-15",
    cliente: MOCK_CLIENTES[0],
  },
  {
    id: "p2",
    cliente_id: "c2",
    nombre: "Farmacia Los Robles — Las Condes",
    direccion: "Av. Apoquindo 4500, Local 12",
    municipio: "Las Condes",
    tipo: "patente_comercial",
    estado: "con_observaciones",
    fecha_inicio: "2025-11-20",
    fecha_estimada: "2026-03-20",
    numero_expediente: "EXP-2025-0987",
    etapa_actual: "Respuesta observaciones",
    created_at: "2025-11-20",
    cliente: MOCK_CLIENTES[1],
  },
  {
    id: "p3",
    cliente_id: "c3",
    nombre: "Strip Center Maipo — Maipú",
    direccion: "Av. Pajaritos 2890",
    municipio: "Maipú",
    tipo: "permiso_edificacion",
    estado: "ingresado",
    fecha_inicio: "2026-02-01",
    fecha_estimada: "2026-09-01",
    numero_expediente: "EXP-2026-0301",
    etapa_actual: "Ingreso DOM",
    created_at: "2026-02-01",
    cliente: MOCK_CLIENTES[2],
  },
  {
    id: "p4",
    cliente_id: "c4",
    nombre: "Supermercado Cordillera — Ñuñoa",
    direccion: "Av. Irarrázaval 3200",
    municipio: "Ñuñoa",
    tipo: "revision_normativa",
    estado: "borrador",
    fecha_inicio: "2026-03-10",
    etapa_actual: "Pre-revisión normativa",
    created_at: "2026-03-10",
    cliente: MOCK_CLIENTES[3],
  },
  {
    id: "p5",
    cliente_id: "c5",
    nombre: "Tienda Aconcagua — Vitacura",
    direccion: "Av. Kennedy 5601, Local 220",
    municipio: "Vitacura",
    tipo: "supervision_apertura",
    estado: "aprobado",
    fecha_inicio: "2025-09-05",
    fecha_estimada: "2025-12-05",
    numero_expediente: "EXP-2025-0654",
    etapa_actual: "Recepción final",
    created_at: "2025-09-05",
    cliente: MOCK_CLIENTES[4],
  },
  {
    id: "p6",
    cliente_id: "c6",
    nombre: "Café Patagonia — Santiago Centro",
    direccion: "Calle Bandera 250, Local 1",
    municipio: "Santiago",
    tipo: "patente_comercial",
    estado: "en_revision",
    fecha_inicio: "2026-01-28",
    fecha_estimada: "2026-07-28",
    numero_expediente: "EXP-2026-0188",
    etapa_actual: "Revisión DOM",
    created_at: "2026-01-28",
    cliente: MOCK_CLIENTES[5],
  },
  {
    id: "p7",
    cliente_id: "c1",
    nombre: "Tienda Retail Andino — La Florida",
    direccion: "Av. Vicuña Mackenna 7110, Local 45",
    municipio: "La Florida",
    tipo: "permiso_edificacion",
    estado: "con_observaciones",
    fecha_inicio: "2025-10-12",
    fecha_estimada: "2026-05-12",
    numero_expediente: "EXP-2025-0820",
    etapa_actual: "Respuesta observaciones",
    created_at: "2025-10-12",
    cliente: MOCK_CLIENTES[0],
  },
  {
    id: "p8",
    cliente_id: "c3",
    nombre: "Local Comercial Maipo — Rancagua",
    direccion: "Av. Cachapoal 1240",
    municipio: "Rancagua",
    tipo: "recepcion_final",
    estado: "aprobado",
    fecha_inicio: "2025-08-22",
    fecha_estimada: "2026-01-22",
    numero_expediente: "EXP-2025-0511",
    etapa_actual: "Recepción final",
    created_at: "2025-08-22",
    cliente: MOCK_CLIENTES[2],
  },
]

// Active project counts per client (mock).
export const PROYECTOS_ACTIVOS_POR_CLIENTE: Record<string, number> = {
  c1: 2,
  c2: 1,
  c3: 2,
  c4: 1,
  c5: 0,
  c6: 1,
}

export const MOCK_ETAPAS: Etapa[] = [
  {
    id: "e1",
    proyecto_id: "p1",
    nombre: "Pre-revisión normativa",
    estado: "completada",
    fecha_inicio: "2026-01-15",
    fecha_fin: "2026-01-22",
    notas: "Uso de suelo conforme. Sin restricciones de altura.",
    orden: 1,
  },
  {
    id: "e2",
    proyecto_id: "p1",
    nombre: "Preparación expediente",
    estado: "completada",
    fecha_inicio: "2026-01-23",
    fecha_fin: "2026-02-10",
    notas: "Planos de arquitectura y memoria entregados por el cliente.",
    orden: 2,
  },
  {
    id: "e3",
    proyecto_id: "p1",
    nombre: "Ingreso DOM",
    estado: "completada",
    fecha_inicio: "2026-02-12",
    fecha_fin: "2026-02-12",
    notas: "Ingresado presencialmente. Comprobante N° 0142.",
    orden: 3,
  },
  {
    id: "e4",
    proyecto_id: "p1",
    nombre: "Revisión DOM",
    estado: "en_curso",
    fecha_inicio: "2026-02-15",
    notas: "En revisión por el arquitecto revisor de la DOM.",
    orden: 4,
  },
  {
    id: "e5",
    proyecto_id: "p1",
    nombre: "Respuesta observaciones",
    estado: "pendiente",
    orden: 5,
  },
  {
    id: "e6",
    proyecto_id: "p1",
    nombre: "Aprobación",
    estado: "pendiente",
    orden: 6,
  },
  {
    id: "e7",
    proyecto_id: "p1",
    nombre: "Recepción final",
    estado: "pendiente",
    orden: 7,
  },
]

export const MOCK_COMUNICACIONES: Comunicacion[] = [
  {
    id: "co1",
    proyecto_id: "p1",
    fecha: "2026-02-20",
    tipo: "email",
    asunto: "Solicitud de aclaración de planos",
    descripcion:
      "El revisor de la DOM solicitó aclarar la cota de la fachada norte. Se reenviaron los planos corregidos.",
    contacto: "DOM Providencia",
    created_at: "2026-02-20",
  },
  {
    id: "co2",
    proyecto_id: "p1",
    fecha: "2026-02-14",
    tipo: "llamada",
    asunto: "Confirmación de ingreso de expediente",
    descripcion:
      "Llamada a la oficina de partes para confirmar recepción del expediente físico.",
    contacto: "Oficina de Partes DOM",
    created_at: "2026-02-14",
  },
  {
    id: "co3",
    proyecto_id: "p1",
    fecha: "2026-01-30",
    tipo: "visita",
    asunto: "Visita técnica al local",
    descripcion:
      "Visita en terreno con el cliente para verificar condiciones existentes antes de preparar el expediente.",
    contacto: "Carolina Fuentes",
    created_at: "2026-01-30",
  },
]

export const MOCK_DOCUMENTOS: Documento[] = [
  {
    id: "d1",
    proyecto_id: "p1",
    nombre: "Planos_arquitectura_v3.pdf",
    tipo: "Planos de arquitectura",
    url: "#",
    tamaño: 4200000,
    created_at: "2026-02-10",
  },
  {
    id: "d2",
    proyecto_id: "p1",
    nombre: "CIP_Providencia.pdf",
    tipo: "Certificado de Informaciones Previas",
    url: "#",
    tamaño: 880000,
    created_at: "2026-01-20",
  },
  {
    id: "d3",
    proyecto_id: "p1",
    nombre: "Memoria_calculo.docx",
    tipo: "Memoria de cálculo",
    url: "#",
    tamaño: 320000,
    created_at: "2026-02-08",
  },
  {
    id: "d4",
    proyecto_id: "p1",
    nombre: "Especificaciones_tecnicas.xlsx",
    tipo: "Especificaciones técnicas",
    url: "#",
    tamaño: 150000,
    created_at: "2026-02-09",
  },
]

export interface MunicipioInfo extends Municipio {
  plataforma_tipo: "DOM en Línea" | "Presencial"
}

export const MOCK_MUNICIPIOS: MunicipioInfo[] = [
  {
    id: "m1",
    nombre: "Santiago",
    region: "Metropolitana",
    dom_telefono: "+56 2 2713 6000",
    dom_email: "dom@munistgo.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 180,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
      { nombre: "Formulario único de edificación", obligatorio: true },
    ],
  },
  {
    id: "m2",
    nombre: "Providencia",
    region: "Metropolitana",
    dom_telefono: "+56 2 2654 4000",
    dom_email: "obras@providencia.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 90,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://dom.providencia.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de avalúo fiscal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m3",
    nombre: "Las Condes",
    region: "Metropolitana",
    dom_telefono: "+56 2 2950 0000",
    dom_email: "obras@lascondes.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 120,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://domenlinea.lascondes.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Estudio de impacto vial (si aplica)", obligatorio: false },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
  {
    id: "m4",
    nombre: "Maipú",
    region: "Metropolitana",
    dom_telefono: "+56 2 2677 6000",
    dom_email: "dom@maipu.cl",
    dom_horario: "Lun a Vie 8:30 - 13:30",
    plazo_tipico_dias: 210,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de número municipal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m5",
    nombre: "Ñuñoa",
    region: "Metropolitana",
    dom_telefono: "+56 2 2973 3000",
    dom_email: "obras@nunoa.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 150,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
  {
    id: "m6",
    nombre: "Vitacura",
    region: "Metropolitana",
    dom_telefono: "+56 2 2419 6000",
    dom_email: "dom@vitacura.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 60,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://domenlinea.vitacura.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Certificado de avalúo fiscal", obligatorio: true },
    ],
  },
  {
    id: "m7",
    nombre: "San Miguel",
    region: "Metropolitana",
    dom_telefono: "+56 2 2550 8000",
    dom_email: "obras@sanmiguel.cl",
    dom_horario: "Lun a Vie 8:30 - 13:30",
    plazo_tipico_dias: 180,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de número municipal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m8",
    nombre: "Pudahuel",
    region: "Metropolitana",
    dom_telefono: "+56 2 2440 9000",
    dom_email: "dom@pudahuel.cl",
    dom_horario: "Lun a Vie 8:30 - 13:30",
    plazo_tipico_dias: 240,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
  {
    id: "m9",
    nombre: "La Florida",
    region: "Metropolitana",
    dom_telefono: "+56 2 2892 0000",
    dom_email: "obras@laflorida.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 200,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de avalúo fiscal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m10",
    nombre: "Rancagua",
    region: "O'Higgins",
    dom_telefono: "+56 72 220 7000",
    dom_email: "dom@rancagua.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 150,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://domenlinea.rancagua.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
]

// ---- CRM MOCK DATA ----
export const MOCK_PROSPECTOS: Prospecto[] = [
  {
    id: 'p1',
    empresa: 'Farmacias SaludVida SpA',
    contacto_nombre: 'Andrés Muñoz',
    cargo: 'Gerente de Expansión',
    email: 'amunoz@saludvida.cl',
    telefono: '+56 9 7654 3210',
    fuente: 'linkedin',
    etapa: 'propuesta_enviada',
    valor_estimado: 1800000,
    municipios_interes: ['Maipú', 'Pudahuel', 'La Florida'],
    notas: 'Planean abrir 8 locales este año. Muy interesados en el servicio de gestión completa.',
    proximo_contacto: '2026-06-25',
    created_at: '2026-05-15',
    actividades: [
      { id: 'a1', prospecto_id: 'p1', tipo: 'linkedin', descripcion: 'Envié mensaje de conexión con pitch', fecha: '2026-05-15', resultado: 'Aceptó la conexión' },
      { id: 'a2', prospecto_id: 'p1', tipo: 'llamada', descripcion: 'Llamada de 20 min. Interesado, quiere propuesta formal', fecha: '2026-05-22', resultado: 'Acordamos enviar propuesta' },
      { id: 'a3', prospecto_id: 'p1', tipo: 'email', descripcion: 'Envié propuesta PDF para 3 locales en RM', fecha: '2026-06-02', resultado: 'Abrió el email (confirmado)' },
    ],
  },
  {
    id: 'p2',
    empresa: 'Strip Center Los Boldos',
    contacto_nombre: 'Patricia Hermosilla',
    cargo: 'Directora Comercial',
    email: 'phermosilla@losboldos.cl',
    telefono: '+56 2 2987 6543',
    fuente: 'referido',
    etapa: 'reunion_agendada',
    valor_estimado: 2500000,
    municipios_interes: ['Las Condes', 'Vitacura'],
    notas: 'Referida por Rodrigo Salinas (Comercial Los Robles). Maneja 3 strip centers.',
    proximo_contacto: '2026-06-22',
    created_at: '2026-06-01',
    actividades: [
      { id: 'a4', prospecto_id: 'p2', tipo: 'email', descripcion: 'Primer contacto vía referido de Rodrigo', fecha: '2026-06-01', resultado: 'Respondió positivo' },
      { id: 'a5', prospecto_id: 'p2', tipo: 'whatsapp', descripcion: 'Confirmamos reunión para el 22/06', fecha: '2026-06-10', resultado: 'Confirmada' },
    ],
  },
  {
    id: 'p3',
    empresa: 'OK Market (expansión 2026)',
    contacto_nombre: 'Felipe Torres',
    cargo: 'Jefe de Desarrollo',
    email: 'ftorres@okmarket.cl',
    telefono: '+56 9 5432 1098',
    fuente: 'linkedin',
    etapa: 'contactado',
    valor_estimado: 4000000,
    municipios_interes: ['Ñuñoa', 'San Miguel', 'Santiago'],
    notas: 'Ex-empleador. Tienen plan de 15 aperturas. Espera aprobación de presupuesto.',
    proximo_contacto: '2026-07-01',
    created_at: '2026-06-05',
    actividades: [
      { id: 'a6', prospecto_id: 'p3', tipo: 'linkedin', descripcion: 'DM directo. Se acordó del trabajo anterior.', fecha: '2026-06-05', resultado: 'Respuesta cálida, pendiente budget' },
    ],
  },
  {
    id: 'p4',
    empresa: 'Cervecería Artesanal Cordillera',
    contacto_nombre: 'Javiera Espinoza',
    cargo: 'Socia Fundadora',
    email: 'javiera@cerveceriacordillera.cl',
    telefono: '+56 9 8765 4321',
    fuente: 'evento',
    etapa: 'negociando',
    valor_estimado: 900000,
    municipios_interes: ['Providencia', 'Ñuñoa'],
    notas: 'Conocida en evento de la CChC. Primer local, nunca ha tramitado permisos. Alto potencial de fidelización.',
    proximo_contacto: '2026-06-20',
    created_at: '2026-05-28',
    actividades: [
      { id: 'a7', prospecto_id: 'p4', tipo: 'reunion', descripcion: 'Reunión en oficina de ella. Presenté el proceso completo.', fecha: '2026-06-08', resultado: 'Quiere ajuste en precio' },
      { id: 'a8', prospecto_id: 'p4', tipo: 'whatsapp', descripcion: 'Envié propuesta revisada con 10% dto primer cliente', fecha: '2026-06-15', resultado: 'Estudiando' },
    ],
  },
  {
    id: 'p5',
    empresa: 'Estudio Arquitectura Brennan & Cia',
    contacto_nombre: 'Matías Brennan',
    cargo: 'Socio Principal',
    email: 'mbrennan@brennanArq.cl',
    fuente: 'linkedin',
    etapa: 'ganado',
    valor_estimado: 1200000,
    municipios_interes: ['Las Condes', 'Vitacura', 'Providencia'],
    notas: 'Primer cliente cerrado. Retainer mensual para 2 locales. Excelente referenciador.',
    created_at: '2026-05-01',
    actividades: [
      { id: 'a9', prospecto_id: 'p5', tipo: 'reunion', descripcion: 'Primera reunión. Presenté portafolio.', fecha: '2026-05-05', resultado: 'Positivo' },
      { id: 'a10', prospecto_id: 'p5', tipo: 'email', descripcion: 'Envié propuesta retainer mensual', fecha: '2026-05-10', resultado: 'Aceptada' },
      { id: 'a11', prospecto_id: 'p5', tipo: 'nota', descripcion: 'Firmado contrato. Inicio el 01/06.', fecha: '2026-05-18', resultado: 'Cerrado ✓' },
    ],
  },
  {
    id: 'p6',
    empresa: 'Cadena Ropa Tempo Chile',
    contacto_nombre: 'Ignacio Saavedra',
    cargo: 'Gerente General',
    email: 'isaavedra@tempochile.cl',
    telefono: '+56 2 2111 2222',
    fuente: 'web',
    etapa: 'nuevo_contacto',
    valor_estimado: 3500000,
    municipios_interes: ['Maipú', 'La Florida', 'Pudahuel', 'Rancagua'],
    notas: 'Llenó formulario en la web. Plan de expansión a tiendas en malls regionales.',
    created_at: '2026-06-17',
    actividades: [],
  },
  {
    id: 'p7',
    empresa: 'Clínica Dental SmileCL',
    contacto_nombre: 'Dr. Héctor Vidal',
    cargo: 'Director Médico',
    email: 'hvidal@smilecl.cl',
    fuente: 'referido',
    etapa: 'descartado',
    notas: 'No cumple el perfil — son clínicas, no retail. El proceso DOM es diferente. Derivé a otro colega.',
    created_at: '2026-05-20',
    actividades: [
      { id: 'a12', prospecto_id: 'p7', tipo: 'llamada', descripcion: 'Llamada de calificación. No es el perfil correcto.', fecha: '2026-05-21', resultado: 'Descartado' },
    ],
  },
]
