export interface EstadisticaMunicipio {
  nombre: string
  region: string
  tiempoPromedioHabiles: number // business days average
  tiempoMedianoHabiles: number
  tasaObservaciones: number // 0-1, percentage of projects that get observations
  tiposObservacionFrequentes: string[]
  totalProyectos: number // anonymized sample size
  cumplimientoPlazoLey: number // 0-1, % of cases where DOM met legal deadline
  calificacion: 1 | 2 | 3 | 4 | 5 // 1=slowest, 5=fastest/best
  notas: string
  mesesMasAgiles: string[]
  mesesMasLentos: string[]
}

export const ESTADISTICAS_MUNICIPIOS: EstadisticaMunicipio[] = [
  {
    nombre: 'Providencia',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 31,
    tiempoMedianoHabiles: 28,
    tasaObservaciones: 0.41,
    tiposObservacionFrequentes: ['Rasantes (Art. 2.6.3)', 'FOS excedido', 'Distanciamientos'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.72,
    calificacion: 3,
    notas: 'DOM con sistema REVI implementado. Observaciones tienden a ser muy técnicas y bien justificadas.',
    mesesMasAgiles: ['Enero', 'Febrero', 'Agosto'],
    mesesMasLentos: ['Marzo', 'Junio', 'Noviembre'],
  },
  {
    nombre: 'Las Condes',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 22,
    tiempoMedianoHabiles: 19,
    tasaObservaciones: 0.28,
    tiposObservacionFrequentes: ['Documentos incompletos', 'Especificaciones técnicas', 'Certificado dominio'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.88,
    calificacion: 5,
    notas: 'Una de las DOMs más ágiles de la RM. Alta digitalización. DOM en Línea funcionando bien.',
    mesesMasAgiles: ['Enero', 'Julio', 'Agosto'],
    mesesMasLentos: ['Diciembre', 'Marzo'],
  },
  {
    nombre: 'Vitacura',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 26,
    tiempoMedianoHabiles: 24,
    tasaObservaciones: 0.35,
    tiposObservacionFrequentes: ['Memoria de entorno urbano', 'Rasantes', 'FOS zona R1'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.81,
    calificacion: 4,
    notas: 'Requiere "Memoria de entorno urbano" en muchos proyectos (requisito adicional local). Altos estándares de presentación.',
    mesesMasAgiles: ['Febrero', 'Agosto'],
    mesesMasLentos: ['Marzo', 'Septiembre'],
  },
  {
    nombre: 'Ñuñoa',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 27,
    tiempoMedianoHabiles: 25,
    tasaObservaciones: 0.38,
    tiposObservacionFrequentes: ['Uso de suelo', 'Alturas máximas', 'Estacionamientos'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.75,
    calificacion: 3,
    notas: 'Zona con muchos proyectos de densificación. Observaciones frecuentes por altura en zonas residenciales.',
    mesesMasAgiles: ['Enero', 'Agosto'],
    mesesMasLentos: ['Julio', 'Octubre'],
  },
  {
    nombre: 'La Florida',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 35,
    tiempoMedianoHabiles: 33,
    tasaObservaciones: 0.45,
    tiposObservacionFrequentes: ['Documentos faltantes', 'Planos incompletos', 'Presupuesto de obra'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.58,
    calificacion: 2,
    notas: 'DOM con alta carga de trabajo. Frecuentes incumplimientos del plazo Ley 21.718. Considerar Revisor Independiente.',
    mesesMasAgiles: ['Febrero', 'Agosto'],
    mesesMasLentos: ['Marzo', 'Octubre', 'Noviembre'],
  },
  {
    nombre: 'Maipú',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 33,
    tiempoMedianoHabiles: 30,
    tasaObservaciones: 0.39,
    tiposObservacionFrequentes: ['FOS excedido', 'Accesibilidad universal', 'Instalaciones sanitarias'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.62,
    calificacion: 2,
    notas: 'DOM con sistema REVI implementado para revisores. Alta demanda de proyectos residenciales.',
    mesesMasAgiles: ['Enero', 'Julio'],
    mesesMasLentos: ['Marzo', 'Diciembre'],
  },
  {
    nombre: 'Santiago',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 29,
    tiempoMedianoHabiles: 27,
    tasaObservaciones: 0.33,
    tiposObservacionFrequentes: ['Uso de suelo mixto', 'Altura edificación', 'Estacionamientos'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.79,
    calificacion: 3,
    notas: 'Centro histórico con normativas especiales. Muchos proyectos de uso mixto.',
    mesesMasAgiles: ['Enero', 'Agosto'],
    mesesMasLentos: ['Junio', 'Septiembre'],
  },
  {
    nombre: 'San Miguel',
    region: 'Metropolitana',
    tiempoPromedioHabiles: 24,
    tiempoMedianoHabiles: 22,
    tasaObservaciones: 0.31,
    tiposObservacionFrequentes: ['Documentos incompletos', 'Rasantes'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.84,
    calificacion: 4,
    notas: 'DOM eficiente y bien organizada. Buenos tiempos de respuesta.',
    mesesMasAgiles: ['Enero', 'Agosto', 'Septiembre'],
    mesesMasLentos: ['Diciembre', 'Marzo'],
  },
  {
    nombre: 'Temuco',
    region: 'Araucanía',
    tiempoPromedioHabiles: 38,
    tiempoMedianoHabiles: 35,
    tasaObservaciones: 0.47,
    tiposObservacionFrequentes: ['Normativa PRC desactualizado', 'Distanciamientos', 'Estudio de impacto'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.61,
    calificacion: 2,
    notas: 'DOM con alta carga. PRC de Temuco requiere verificaciones frecuentes por zonas de riesgo.',
    mesesMasAgiles: ['Enero', 'Julio'],
    mesesMasLentos: ['Marzo', 'Octubre'],
  },
  {
    nombre: 'Viña del Mar',
    region: 'Valparaíso',
    tiempoPromedioHabiles: 29,
    tiempoMedianoHabiles: 26,
    tasaObservaciones: 0.36,
    tiposObservacionFrequentes: ['Zonas de protección costera', 'Rasantes', 'Accesibilidad universal'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.77,
    calificacion: 4,
    notas: 'DOM con buena respuesta. Atención especial a normativas de zona costera y turística.',
    mesesMasAgiles: ['Febrero', 'Agosto', 'Septiembre'],
    mesesMasLentos: ['Enero', 'Diciembre'],
  },
  {
    nombre: 'Rancagua',
    region: "O'Higgins",
    tiempoPromedioHabiles: 34,
    tiempoMedianoHabiles: 31,
    tasaObservaciones: 0.42,
    tiposObservacionFrequentes: ['Documentos incompletos', 'Planos de instalaciones', 'FOS'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.65,
    calificacion: 3,
    notas: 'DOM regional con experiencia en proyectos industriales. Tramitación en DOM en Línea disponible.',
    mesesMasAgiles: ['Febrero', 'Agosto'],
    mesesMasLentos: ['Marzo', 'Junio'],
  },
  {
    nombre: 'Concepción',
    region: 'Biobío',
    tiempoPromedioHabiles: 36,
    tiempoMedianoHabiles: 33,
    tasaObservaciones: 0.44,
    tiposObservacionFrequentes: ['Microzonificación sísmica', 'Distanciamientos', 'Uso de suelo'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.63,
    calificacion: 2,
    notas: 'DOM importante de la región. Alta sismicidad exige estudios adicionales frecuentes.',
    mesesMasAgiles: ['Enero', 'Agosto'],
    mesesMasLentos: ['Mayo', 'Octubre'],
  },
  {
    nombre: 'Puerto Montt',
    region: 'Los Lagos',
    tiempoPromedioHabiles: 41,
    tiempoMedianoHabiles: 38,
    tasaObservaciones: 0.51,
    tiposObservacionFrequentes: ['Suelos de relleno', 'Pendientes > 30°', 'Estudio de mecánica de suelos'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.55,
    calificacion: 2,
    notas: 'Proyectos en ladera y terrenos con relleno son frecuentes. Estudios de suelo son casi siempre requeridos.',
    mesesMasAgiles: ['Enero', 'Febrero'],
    mesesMasLentos: ['Junio', 'Julio'],
  },
  {
    nombre: 'Valparaíso',
    region: 'Valparaíso',
    tiempoPromedioHabiles: 45,
    tiempoMedianoHabiles: 40,
    tasaObservaciones: 0.58,
    tiposObservacionFrequentes: ['Zona típica / patrimonio', 'Pendientes extremas', 'Accesibilidad', 'Certificado de patrimonio'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.48,
    calificacion: 1,
    notas: 'DOM con alta complejidad por Zona Típica UNESCO. Proyectos patrimoniales requieren informes del CMN. Una de las más lentas del país.',
    mesesMasAgiles: ['Enero', 'Agosto'],
    mesesMasLentos: ['Marzo', 'Junio', 'Noviembre'],
  },
  {
    nombre: 'Talca',
    region: 'Maule',
    tiempoPromedioHabiles: 30,
    tiempoMedianoHabiles: 28,
    tasaObservaciones: 0.37,
    tiposObservacionFrequentes: ['Certificado de dominio vigente', 'Planos de instalaciones', 'Distanciamientos'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.74,
    calificacion: 3,
    notas: 'DOM organizada. Buen uso de DOM en Línea. Reconstrucción post-terremoto mejoró capacidad técnica.',
    mesesMasAgiles: ['Enero', 'Agosto'],
    mesesMasLentos: ['Junio', 'Septiembre'],
  },
  {
    nombre: 'La Serena',
    region: 'Coquimbo',
    tiempoPromedioHabiles: 32,
    tiempoMedianoHabiles: 30,
    tasaObservaciones: 0.39,
    tiposObservacionFrequentes: ['Zona de borde costero', 'Estilo arquitectónico centro histórico', 'Rasantes'],
    totalProyectos: 0,
    cumplimientoPlazoLey: 0.71,
    calificacion: 3,
    notas: 'Centro histórico con normativas especiales. Zona costera con regulaciones adicionales de DIRECTEMAR.',
    mesesMasAgiles: ['Febrero', 'Agosto'],
    mesesMasLentos: ['Enero', 'Julio'],
  },
]

export function getMunicipioStats(nombre: string): EstadisticaMunicipio | null {
  return ESTADISTICAS_MUNICIPIOS.find(m =>
    m.nombre.toLowerCase() === nombre.toLowerCase()
  ) ?? null
}

export function getRanking(): EstadisticaMunicipio[] {
  return [...ESTADISTICAS_MUNICIPIOS].sort((a, b) => b.calificacion - a.calificacion)
}
