import type { Municipio } from "@/types"

export const MUNICIPIOS_PRINCIPALES = [
  "Santiago",
  "Providencia",
  "Las Condes",
  "Maipú",
  "Ñuñoa",
  "Vitacura",
  "San Miguel",
  "Pudahuel",
  "La Florida",
  "Rancagua",
]

export interface MunicipioInfo extends Municipio {
  plataforma_tipo: "DOM en Línea" | "Presencial"
}

export const MUNICIPIOS_INFO: MunicipioInfo[] = [
  {
    id: "m1",
    nombre: "Santiago",
    region: "Metropolitana",
    dom_telefono: "+56 2 2713 6000",
    dom_email: "dom@munistgo.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 180,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
      { nombre: "Formulario único de edificación", obligatorio: true },
    ],
  },
  {
    id: "m2",
    nombre: "Providencia",
    region: "Metropolitana",
    dom_telefono: "+56 2 2654 4000",
    dom_email: "obras@providencia.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 90,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://dom.providencia.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de avalúo fiscal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m3",
    nombre: "Las Condes",
    region: "Metropolitana",
    dom_telefono: "+56 2 2950 0000",
    dom_email: "obras@lascondes.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 120,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://domenlinea.lascondes.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Estudio de impacto vial (si aplica)", obligatorio: false },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
  {
    id: "m4",
    nombre: "Maipú",
    region: "Metropolitana",
    dom_telefono: "+56 2 2677 6000",
    dom_email: "dom@maipu.cl",
    dom_horario: "Lun a Vie 8:30 - 13:30",
    plazo_tipico_dias: 210,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de número municipal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m5",
    nombre: "Ñuñoa",
    region: "Metropolitana",
    dom_telefono: "+56 2 2973 3000",
    dom_email: "obras@nunoa.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 150,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
  {
    id: "m6",
    nombre: "Vitacura",
    region: "Metropolitana",
    dom_telefono: "+56 2 2419 6000",
    dom_email: "dom@vitacura.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 60,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://domenlinea.vitacura.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Certificado de avalúo fiscal", obligatorio: true },
    ],
  },
  {
    id: "m7",
    nombre: "San Miguel",
    region: "Metropolitana",
    dom_telefono: "+56 2 2550 8000",
    dom_email: "obras@sanmiguel.cl",
    dom_horario: "Lun a Vie 8:30 - 13:30",
    plazo_tipico_dias: 180,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de número municipal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m8",
    nombre: "Pudahuel",
    region: "Metropolitana",
    dom_telefono: "+56 2 2440 9000",
    dom_email: "dom@pudahuel.cl",
    dom_horario: "Lun a Vie 8:30 - 13:30",
    plazo_tipico_dias: 240,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
  {
    id: "m9",
    nombre: "La Florida",
    region: "Metropolitana",
    dom_telefono: "+56 2 2892 0000",
    dom_email: "obras@laflorida.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 200,
    plataforma_tipo: "Presencial",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Certificado de avalúo fiscal", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
    ],
  },
  {
    id: "m10",
    nombre: "Rancagua",
    region: "O'Higgins",
    dom_telefono: "+56 72 220 7000",
    dom_email: "dom@rancagua.cl",
    dom_horario: "Lun a Vie 8:30 - 14:00",
    plazo_tipico_dias: 150,
    plataforma_tipo: "DOM en Línea",
    url_dom: "https://domenlinea.rancagua.cl",
    requisitos: [
      { nombre: "Certificado de Informaciones Previas (CIP)", obligatorio: true },
      { nombre: "Planos de arquitectura", obligatorio: true },
      { nombre: "Memoria de cálculo estructural", obligatorio: true },
      { nombre: "Especificaciones técnicas", obligatorio: true },
      { nombre: "Patente del profesional", obligatorio: true },
    ],
  },
]
